// <auto-generated />
using System;
using GdprRecord.Server.Feature.ProcessingActivity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GdprRecord.Server.Feature.ProcessingActivity.Migrations
{
    [DbContext(typeof(ProcessingActivityContext))]
    [Migration("20260408152940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.DataSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.ToTable("DataSubject", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.InternationalRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documentation")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Guarantees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.ToTable("InternationalRecipient", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.PersonalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePeriod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.ToTable("PersonalData", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessingActivity", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.Purpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.ToTable("Purpose", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.ToTable("Recipient", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.SecurityMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.ToTable("SecurityMeasure", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.SensitiveData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePeriod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.ToTable("SensitiveData", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.DataSubject", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", null)
                        .WithMany("CategoriesOfDataSubjects")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.InternationalRecipient", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", null)
                        .WithMany("InternationalRecipients")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.PersonalData", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", null)
                        .WithMany("CategoriesOfPersonalData")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.Purpose", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", null)
                        .WithMany("Purposes")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.Recipient", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", null)
                        .WithMany("Recipients")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.SecurityMeasure", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", null)
                        .WithMany("SecurityMeasures")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.SensitiveData", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", null)
                        .WithMany("CategoriesOfSensitiveData")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.ProcessingActivity.Model.ProcessingActivity", b =>
                {
                    b.Navigation("CategoriesOfDataSubjects");

                    b.Navigation("CategoriesOfPersonalData");

                    b.Navigation("CategoriesOfSensitiveData");

                    b.Navigation("InternationalRecipients");

                    b.Navigation("Purposes");

                    b.Navigation("Recipients");

                    b.Navigation("SecurityMeasures");
                });
#pragma warning restore 612, 618
        }
    }
}
