// <auto-generated />
using GdprRecord.Server.Feature.Organization.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GdprRecord.Server.Feature.Organization.Migrations
{
    [DbContext(typeof(OrganizationContext))]
    [Migration("20240527072755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1");

            modelBuilder.Entity("GdprRecord.Server.Feature.Organization.Model.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControllersRepresentativeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataProtectionOfficerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JointControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.HasIndex("ControllersRepresentativeId");

                    b.HasIndex("DataProtectionOfficerId");

                    b.HasIndex("JointControllerId");

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.Organization.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("GdprRecord.Server.Feature.Organization.Model.Organization", b =>
                {
                    b.HasOne("GdprRecord.Server.Feature.Organization.Model.Person", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId");

                    b.HasOne("GdprRecord.Server.Feature.Organization.Model.Person", "ControllersRepresentative")
                        .WithMany()
                        .HasForeignKey("ControllersRepresentativeId");

                    b.HasOne("GdprRecord.Server.Feature.Organization.Model.Person", "DataProtectionOfficer")
                        .WithMany()
                        .HasForeignKey("DataProtectionOfficerId");

                    b.HasOne("GdprRecord.Server.Feature.Organization.Model.Person", "JointController")
                        .WithMany()
                        .HasForeignKey("JointControllerId");

                    b.Navigation("Controller");

                    b.Navigation("ControllersRepresentative");

                    b.Navigation("DataProtectionOfficer");

                    b.Navigation("JointController");
                });
#pragma warning restore 612, 618
        }
    }
}
